-- V21: the sweep queue's instant stops depending on who is connected.
--
-- `marked_at` is `timestamp` without a zone, and V18 filled it with `DEFAULT clock_timestamp()`.
-- `clock_timestamp()` returns `timestamptz`, so that default carries an *implicit* cast down to
-- `timestamp`, and an implicit cast renders the instant in the session's `TimeZone`. pgjdbc sets
-- that setting from the JVM's default zone on every connection.
--
-- The consequence is a schema that means different things in different rooms. On a developer's
-- machine in Bolivia the JVM is already America/La_Paz, so the column happens to hold La Paz wall
-- time and nothing looks wrong. Deployed with the API in a container running UTC, the same column
-- holds UTC — four hours from the school's clock — while `risk_predictions.last_notified_at` keeps
-- being written by the application off the injected La Paz Clock. Two columns of one schema, on
-- two different wall clocks, and neither of them records which.
--
-- Nothing today compares the two, so this is not a bug being fixed; it is a trap being closed
-- before somebody walks into it, most likely by writing the obvious query that joins them.
--
-- WHAT IS DELIBERATELY NOT DONE HERE:
--
--   * The instant is NOT moved into the application. It stays `clock_timestamp()`, generated by
--     the database inside the statement that writes the row. V18 chose that over CURRENT_TIMESTAMP
--     because the transaction's start time would stamp a long write with an instant from before
--     the sweep read it, and the row would then be cleared having never been predicted. A stamp
--     taken in Java when the call is built, and written some milliseconds later, reopens the same
--     hole from the other side. Only the *rendering* is pinned; the generation stays put.
--
--   * The column is NOT converted to `timestamptz`. It would be the only one in the schema, while
--     some twenty other tables keep `timestamp`, and the Java side would have to change type with
--     it. One zone, stated once, is the cheaper way to make the column mean one thing.
--
-- The table is drained by every sweep and holds at most one row per subject per trimester, so
-- there is nothing to backfill: whatever is in it now is minutes old and about to be deleted.
--
-- Idempotent: SET DEFAULT is absolute, not additive, so a second run writes the same default it
-- already has. Run by hand like every other script in this folder.

ALTER TABLE public.risk_prediction_queue
    ALTER COLUMN marked_at SET DEFAULT (clock_timestamp() AT TIME ZONE 'America/La_Paz');

COMMENT ON COLUMN public.risk_prediction_queue.marked_at IS
    'When the most recent un-swept change arrived, as La Paz wall time. Generated by the database '
    'at write time and pinned to the school zone, so the value does not depend on the TimeZone of '
    'whichever client happens to be connected.';
