package bo.edu.univalle.sis.ue6dejunio_api.integration;

import com.jayway.jsonpath.JsonPath;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.web.servlet.MockMvc;

import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * GET /api/gradebook/annual-centralizer over a real Postgres, asserting the response body and not
 * just its status.
 *
 * <p>The service's arithmetic and the DTO mapping are each proved in isolation with mocks, and
 * both stayed green through a schema they never touched. What only a real database can answer is
 * whether {@code total_score} — a generated column, never written by this code — reaches the
 * averaging at all, and whether the numbers the web reads off this endpoint are the ones the
 * school's sheet would print.
 */
class GradebookAnnualCentralizerIT extends AbstractIntegrationTest {

    @Autowired private MockMvc mvc;

    private UUID director;
    private UUID courseId;

    @BeforeEach
    void seed() {
        director = seedUser("Director", false);
        UUID teacher = seedUser("Teacher", false);
        courseId = seedCourse(teacher, "A");

        UUID classGroupLang = seedClassGroup(courseId, teacher, "Lenguaje");
        UUID classGroupMath = seedClassGroup(courseId, teacher, "Matematicas");

        // Fixed name: the listing sorts by last name, so a generated one would move the row.
        UUID student = seedStudent("Ana", "Perez");
        UUID enrollment = seedEnrollment(student, courseId);

        // academic_scores caps each dimension: being<=10, knowing<=45, doing<=40, deciding<=5,
        // and total_score is generated by the database from the four.
        // Lenguaje graded all three trimesters, 60 each.
        seedAcademicScore(enrollment, classGroupLang, 1,
            new BigDecimal("10"), new BigDecimal("20"), new BigDecimal("25"), new BigDecimal("5"));
        seedAcademicScore(enrollment, classGroupLang, 2,
            new BigDecimal("10"), new BigDecimal("20"), new BigDecimal("25"), new BigDecimal("5"));
        seedAcademicScore(enrollment, classGroupLang, 3,
            new BigDecimal("10"), new BigDecimal("20"), new BigDecimal("25"), new BigDecimal("5"));
        // Matematicas graded only in the first trimester, 27.
        seedAcademicScore(enrollment, classGroupMath, 1,
            new BigDecimal("5"), new BigDecimal("10"), new BigDecimal("10"), new BigDecimal("2"));
    }

    private void seedAcademicScore(UUID enrollmentId, UUID classGroupId, int trimester,
                                   BigDecimal being, BigDecimal knowing, BigDecimal doing,
                                   BigDecimal deciding) {
        jdbc.update(
            "INSERT INTO academic_scores (id_academic_score, id_course_enrollment, id_class_group, "
                + "trimester, score_being, score_knowing, score_doing, score_deciding) "
                + "VALUES (?,?,?,?,?,?,?,?)",
            UUID.randomUUID(), enrollmentId, classGroupId, trimester, being, knowing, doing,
            deciding);
    }

    private String annualBody() throws Exception {
        return mvc.perform(get("/api/gradebook/annual-centralizer")
                .header("Authorization", "Bearer " + tokenFor(director, "Director"))
                .param("id_course", courseId.toString())
                .param("offset", "1")
                .param("limit", "30"))
            .andExpect(status().isOk())
            .andReturn().getResponse().getContentAsString(StandardCharsets.UTF_8);
    }

    /** JSON numbers arrive as Double or BigDecimal depending on the parser; compare by value. */
    private static BigDecimal number(String body, String path) {
        Object raw = JsonPath.read(body, path);
        return raw == null ? null : new BigDecimal(String.valueOf(raw));
    }

    @Test
    void annualCentralizer_readsTheGeneratedTotalIntoEveryAreaAndItsAverage() throws Exception {
        String body = annualBody();

        assertThat((Object) JsonPath.read(body, "$.content[0].fullName")).isNotNull();
        // Ordered by subject name, so the columns cannot shuffle between two loads.
        assertThat((String) JsonPath.read(body, "$.content[0].subjects[0].subjectName"))
            .isEqualTo("Lenguaje");
        assertThat((String) JsonPath.read(body, "$.content[0].subjects[1].subjectName"))
            .isEqualTo("Matematicas");

        // 10 + 20 + 25 + 5, computed by the database and never by this code.
        assertThat(number(body, "$.content[0].subjects[0].trimester1")).isEqualByComparingTo("60");
        assertThat(number(body, "$.content[0].subjects[0].trimester2")).isEqualByComparingTo("60");
        assertThat(number(body, "$.content[0].subjects[0].trimester3")).isEqualByComparingTo("60");
        assertThat(number(body, "$.content[0].subjects[0].average")).isEqualByComparingTo("60.00");
    }

    @Test
    void annualCentralizer_areaGradedInOneTrimesterOnly_leavesTheOthersNull() throws Exception {
        String body = annualBody();

        // Matematicas was never graded after the first trimester. Those cells have to arrive as
        // JSON null, because a zero would tell the school the student failed two trimesters of a
        // subject nobody ever marked.
        assertThat((Object) JsonPath.read(body, "$.content[0].subjects[1].trimester2")).isNull();
        assertThat((Object) JsonPath.read(body, "$.content[0].subjects[1].trimester3")).isNull();
        assertThat(number(body, "$.content[0].subjects[1].trimester1")).isEqualByComparingTo("27");
        assertThat(number(body, "$.content[0].subjects[1].average")).isEqualByComparingTo("27.00");
    }

    @Test
    void annualCentralizer_carriesThreeTrimesterAveragesAndTheFinalOne() throws Exception {
        String body = annualBody();

        assertThat((java.util.List<?>) JsonPath.read(body, "$.content[0].trimesterAverages"))
            .hasSize(3);
        // (60 + 27) / 2, then 60 alone for the trimesters Matematicas is absent from.
        assertThat(number(body, "$.content[0].trimesterAverages[0]"))
            .isEqualByComparingTo("43.50");
        assertThat(number(body, "$.content[0].trimesterAverages[1]"))
            .isEqualByComparingTo("60.00");
        assertThat(number(body, "$.content[0].trimesterAverages[2]"))
            .isEqualByComparingTo("60.00");
        // Mean of the area averages: (60 + 27) / 2.
        assertThat(number(body, "$.content[0].finalAverage")).isEqualByComparingTo("43.50");
    }

    @Test
    void annualCentralizer_pagesLikeTheTrimesterSheet() throws Exception {
        String body = annualBody();

        assertThat(number(body, "$.total")).isEqualByComparingTo("1");
        assertThat(number(body, "$.page")).isEqualByComparingTo("0");
    }
}
